{
 "title": "Wetterdaten",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "wetterdaten",
     "rawSql": "SELECT \n  CASE \n    WHEN Pausenstatus != 0 THEN\n      CASE\n        WHEN Pausenstatus = 1 THEN 'Regenpause!'\n        WHEN Pausenstatus = 2 THEN 'Kältepause!'\n        WHEN Pausenstatus = 3 THEN 'Schönwetterpause!'\n      END\n    ELSE 'Regenpausenanzeiger'\n  END AS Pausenstatus\nFROM wetterdaten.wetterdaten\nORDER BY Zeitstempel DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperatur- und Luftfeuchtigkeitsverlauf",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "wetterdaten",
     "rawSql": "SELECT Temperatur AS \"value\", Zeitstempel AS \"time\" FROM wetterdaten.wetterdaten"
    },
    {
     "dataset": "wetterdaten",
     "rawSql": "SELECT Luftfeuchtigkeit AS \"value\", Zeitstempel AS \"time\" FROM wetterdaten.wetterdaten"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "wetterdaten",
     "rawSql": "SELECT Temperatur FROM wetterdaten.wetterdaten"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "wetterdaten",
     "rawSql": "SELECT Luftfeuchtigkeit FROM wetterdaten.wetterdaten"
    }
   ]
  }
 ]
}